//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sport_Gorkavya.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportTovar
    {
        public int id { get; set; }
        public string naimenov { get; set; }
        public int kolichestvo { get; set; }
        public decimal cena { get; set; }
        public string brend { get; set; }
        public string PazmerObuvi { get; set; }
        public int StatusID { get; set; }
        public int DostavkaID { get; set; }
        public int PynkkVidachi { get; set; }
    
        public virtual Dostavka Dostavka { get; set; }
        public virtual Pynkt Pynkt { get; set; }
        public virtual Status Status { get; set; }
    }
}
